import path from 'path';
import fs from 'fs';
import { defineConfig, loadEnv, Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// Dev-only plugin to save Firebase config from the Admin Panel
function firebaseConfigPlugin(): Plugin {
  const configPath = () => path.resolve(__dirname, 'public/firebase-config.js');

  // Read the current config
  const readCurrentConfig = () => {
    try {
      const content = fs.readFileSync(configPath(), 'utf-8');
      const fbMatch = content.match(/window\.__FIREBASE_CONFIG__\s*=\s*(\{[\s\S]*?\});/);

      let firebaseConfig = { apiKey: '', authDomain: '', projectId: '', storageBucket: '', messagingSenderId: '', appId: '' };
      if (fbMatch) {
        try {
          const cleaned = fbMatch[1].replace(/(\w+):/g, '"$1":').replace(/'/g, '"');
          firebaseConfig = JSON.parse(cleaned);
        } catch { }
      }
      return firebaseConfig;
    } catch {
      return { apiKey: '', authDomain: '', projectId: '', storageBucket: '', messagingSenderId: '', appId: '' };
    }
  };

  // Write config to file
  const writeConfigFile = (firebaseConfig: any) => {
    const content = `// Firebase Runtime Configuration
// This file is auto-generated by the Admin Panel's Firebase Setup tab.
// Do NOT edit manually — use the Admin Panel instead.

window.__FIREBASE_CONFIG__ = {
    apiKey: "${firebaseConfig.apiKey || ''}",
    authDomain: "${firebaseConfig.authDomain || ''}",
    projectId: "${firebaseConfig.projectId || ''}",
    storageBucket: "${firebaseConfig.storageBucket || ''}",
    messagingSenderId: "${firebaseConfig.messagingSenderId || ''}",
    appId: "${firebaseConfig.appId || ''}"
};
`;
    fs.writeFileSync(configPath(), content, 'utf-8');
  };

  return {
    name: 'firebase-config-api',
    configureServer(server) {
      // GET current Firebase config
      server.middlewares.use('/api/firebase-config', (req, res, next) => {
        if (req.method !== 'GET') return next();
        const firebaseConfig = readCurrentConfig();
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify(firebaseConfig));
      });

      // POST save Firebase config
      server.middlewares.use('/api/save-firebase-config', (req, res, next) => {
        if (req.method !== 'POST') return next();
        let body = '';
        req.on('data', (chunk: Buffer) => { body += chunk.toString(); });
        req.on('end', () => {
          try {
            const newFirebaseConfig = JSON.parse(body);
            writeConfigFile(newFirebaseConfig);
            res.setHeader('Content-Type', 'application/json');
            res.end(JSON.stringify({ success: true }));
          } catch (e: any) {
            res.statusCode = 400;
            res.end(JSON.stringify({ error: e.message }));
          }
        });
      });
    }
  };
}


export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, '.', '');
  return {
    server: {
      port: 3000,
      host: '0.0.0.0',
    },
    plugins: [react(), firebaseConfigPlugin()],
    define: {
      'import.meta.env.VITE_GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY || env.VITE_GEMINI_API_KEY)
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      }
    }
  };
});
